# Generated by Django 5.1 on 2024-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_remove_newslettersubscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.TextField(blank=True, default=''),
        ),
    ]
