# Generated by Django 5.1 on 2024-11-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_body_newsletter_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersent',
            name='newsletter_subscription',
        ),
        migrations.AddField(
            model_name='newslettersent',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
