# Generated by Django 5.1 on 2024-10-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
