# Generated by Django 5.1 on 2024-11-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
